/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dance.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/dance.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Kachujin">
            <skinnedMesh name="Kachujin_1" geometry={nodes.Kachujin_1.geometry} material={materials.kachujin_MAT} skeleton={nodes.Kachujin_1.skeleton} />
            <skinnedMesh name="Kachujin_2" geometry={nodes.Kachujin_2.geometry} material={materials.kachujin_MAT_} skeleton={nodes.Kachujin_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dance.glb')

export default Model;